[package]
name = "ProjectNeon"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.4"
rand = "0.9.2"

[[bin]]
name = "relay"
path = "src/relay.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "host"
path = "src/host.rs"
